# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160326_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='disqus_shortname',
            field=models.CharField(blank=True, help_text='Shortname proporcionado por disqus', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_disqus',
            field=models.BooleanField(default=False),
        ),
    ]
