# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_flatpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='gplus',
            field=models.URLField(blank=True, help_text='Google Plus', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='instagram',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pinterest',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='twitter',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
