# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-04 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20161105_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='google_analytics',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
