# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='abstract',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
