# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-14 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
