# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_playlist_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías de videos',
                'verbose_name': 'Categoría de videos',
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='category',
            field=models.ManyToManyField(help_text='Categorías a la que pertenece', to='videos.VideoCategory'),
        ),
    ]
