# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20180611_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='category',
            new_name='categories',
        ),
    ]
