# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-14 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20180611_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
