# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 03:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del trabajo', max_length=800, verbose_name='Título')),
                ('description', models.TextField(help_text='Describa de manera clara el puesto de trabajo', max_length=2000, verbose_name='Descripción')),
                ('salary', models.CharField(help_text='Describe el salario a ofrecer por la vacante', max_length=600, verbose_name='Salario')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(blank=True, help_text='Ubicación del puesto', max_length=500, null=True, verbose_name='Dirección')),
                ('remote_working', models.BooleanField(default=False, help_text='¿Se acepta trabajo desde casa?', verbose_name='Remoto')),
                ('work_schedule', models.IntegerField(choices=[(1, 'Tiempo completo'), (0, 'Tiempo parcial')], default=1, verbose_name='Horario')),
                ('company_name', models.CharField(help_text='Nombre de la empresa que propone la vacante', max_length=1000, verbose_name='Nombre de la empresa')),
                ('contact_email', models.CharField(help_text='Email donde serán enviadas las aplicaciones', max_length=1000, verbose_name='Email de contacto')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('status', models.IntegerField(choices=[(0, 'Rechazado'), (1, 'Aprobado'), (2, 'Por aprobar')], default=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('approval_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de aprobación')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleo',
                'verbose_name_plural': 'Empleos',
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la categoría del trabajo', max_length=500)),
            ],
            options={
                'verbose_name': 'Categoría de empleo',
                'verbose_name_plural': 'Categorías de empleo',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(help_text='Categorías a la que aplica la vacante', to='jobboard.JobCategory', verbose_name='Categorías'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(help_text='Usuario que crea la vacante', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
