# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='num_of_views',
            field=models.IntegerField(default=0, help_text='Número de impresiones de tu job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'Rechazado'), (1, 'Aprobado'), (2, 'Borrador'), (3, 'En revisión')], default=2),
        ),
    ]
